In [13]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Numerical Python also known as Numpy it have functionality called numpy arrat which is basically like python list but it's 50x fater than python list. it was created in 2005 by developer called travis oliphant, it's deep down written in c++ language

In [2]:
#here we import numpy
import numpy as np

**her we do slicing and indexeing in numpy array**

In [23]:
ar1 = np.array([12,54,78,90,1])
print(ar1[1])
print(type(ar1))
print(ar1[-1])
print(ar1[1:4])

54
<class 'numpy.ndarray'>
1
[54 78 90]


1D Array

In [3]:
arr = np.array([11,22,33])
print(arr)

[11 22 33]


2D array

In [10]:
arr2 = np.array([[22,32,43],[41,56,87],[44,5,7]])
# print(arr2[0][2])
# print(arr2[2][1])
# print(arr2.ndim)
print(arr2)

[[22 32 43]
 [41 56 87]
 [44  5  7]]


**Stastical operation**

In [ ]:
arr9 = np.array([23,11,9,21,32,8,7])
# np.mean(arr9)  #average value
# np.sum(arr9)  #here it sum
# np.max(arr9)  #here we get maximum value
# np.min(arr9)  #here we get minimum value

np.int64(7)

**Mathematical operations**

In [15]:
a = np.array([21,11,4])
b = np.array([20,10,6])

In [16]:
np.add(a,b)

array([41, 21, 10])

In [17]:
np.subtract(a,b)

array([ 1,  1, -2])

In [18]:
np.multiply(a,b)

array([420, 110,  24])

In [19]:
np.divide(a,b)

array([1.05      , 1.1       , 0.66666667])