In [1]:
print("Hello World")

Hello World


**This is Markdown cell**

In [2]:
a = 12
print(a)

12


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


**Numerical Python is also know as Numpy, so basically it was created becuse it is 50x faster than normal python list, it was created in year 2005 by developer called travis oliphant it is deep down written language C which make it more faster and reliable**

In [1]:
import numpy as np

In [2]:
a1 = np.array([12,45,78,90])
print(a1[::-1])

[90 78 45 12]


In [11]:
print(a1.ndim)

1


In [3]:
a2= np.array([[23,45,78],[11,89,21],[11,89,21]])
print(a2.ndim)
print(a2[1][1])

2
89


**Stastical Operation**

In [10]:
ar2 = np.array([21,45,98,11,10])

In [11]:
np.max(ar2)

np.int64(98)

In [ ]:
np.min(ar2)

np.int64(10)

In [12]:
np.mean(ar2)

np.float64(37.0)

In [13]:
np.median(ar2)

np.float64(21.0)

**Mathamatical operation**

In [15]:
ar3 = np.array([2,4,6,8])
ar4 = np.array([10,12,14,16])

In [16]:
np.add(ar3,ar4)

array([12, 16, 20, 24])

In [17]:
np.subtract(ar3,ar4)

array([-8, -8, -8, -8])

In [18]:
np.multiply(ar3,ar4)

array([ 20,  48,  84, 128])

In [19]:
np.divide(ar3,ar4)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

**Resahping array**

In [23]:
arr = np.array([10,20,30,40,50,60])
new_a = arr.reshape(3,2)
print(new_a)

[[10 20]
 [30 40]
 [50 60]]


In [26]:
arr2 = np.array([[10,20,30],[40,50,60]])
f_array = arr2.flatten()
print(f_array)

[10 20 30 40 50 60]
