In [ ]:
#Here we download numpy by using pip
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


**Numerical Python also know as numpy was created by scientist namely travis oliphan in 2005 his main motive was to reduce the time complexity so thats why he create a numpy array which basically works like normal python list but it's 50x faster than normal python list**

In [ ]:
#Here we inmport numpy
import numpy as np

**Numpy array stores multiple items in a single variable. It's Homegenous**

In [11]:
arr = np.array([2,56,89,11])
print(arr[1])
print(arr[-1])
print(arr[1:3])
print(arr[1:])
print(arr[:3])
print(arr[: :-1])

56
11
[56 89]
[56 89 11]
[ 2 56 89]
[11 89 56  2]


In [4]:
ar1 = np.array([22,78,90,61,23])
print(ar1.ndim)

1
