In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Numerical Python also known as Numpy it have functionality called numpy arrat which is basically like python list but it's 50x fater than python list. it was created in 2005 by developer called travis oliphant, it's deep down written in c++ language

In [1]:
#here we import numpy
import numpy as np

**her we do slicing and indexeing in numpy array**

In [ ]:
ar1 = np.array([12,54,78,90,1])
print(ar1[1])
print(type(ar1))
print(ar1[-1])
print(ar1[1:4])

54
<class 'numpy.ndarray'>
1
[54 78 90]


1D Array

In [ ]:
arr = np.array([11,22,33])
print(arr)

[11 22 33]


2D array

In [ ]:
arr2 = np.array([[22,32,43],[41,56,87],[44,5,7]])
# print(arr2[0][2])
# print(arr2[2][1])
# print(arr2.ndim)
print(arr2)

[[22 32 43]
 [41 56 87]
 [44  5  7]]


**Stastical operation**

In [ ]:
arr9 = np.array([23,11,9,21,32,8,7])
# np.mean(arr9)  #average value
# np.sum(arr9)  #here it sum
# np.max(arr9)  #here we get maximum value
# np.min(arr9)  #here we get minimum value

np.int64(7)

**Mathematical operations**

In [ ]:
a = np.array([21,11,4])
b = np.array([20,10,6])

In [ ]:
np.add(a,b)

array([41, 21, 10])

In [ ]:
np.subtract(a,b)

array([ 1,  1, -2])

In [ ]:
np.multiply(a,b)

array([420, 110,  24])

In [ ]:
np.divide(a,b)

array([1.05      , 1.1       , 0.66666667])

In [ ]:
a = np.array([25,4,2,64])

In [ ]:
np.power(a,2)

array([ 625,   16,    4, 4096])

In [ ]:
np.power(a,3)

array([ 15625,     64,      8, 262144])

In [ ]:
np.sqrt(a)

array([5.        , 2.        , 1.41421356, 8.        ])

**Random number gives randomly some number**

In [ ]:
x = np.random.rand()
print(x)

0.6259198859298967


In [ ]:
x= np.random.rand(3)
print(x)

[0.7718719  0.3569604  0.52640912]


**Here we are giving range from where to start and where to end**


In [ ]:
y= np.random.randint(1,20,size=4)
print(y)

[12  6  9  7]


In [ ]:
y= np.random.randint(1000,9999,size=3)  #here we generate random 4 digit number
print(y)

[8302 6263 8810 6856 1532 1554 2156 9732 3234 2461]


In [ ]:
z = np.random.randint(100000,999999,size=2) #here we genrate random 6 digit number 
print(z)

[240603 782264]


In [ ]:
y1 = np.random.randn(2)
print(y1)

[-0.72328235  1.18311488]


**Array Manipulation**

In [ ]:
a1 = np.array([1,2,3,4])
arr = np.append(a1,[5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
a2 = np.array([[10,20,30],[40,50,60]])
arr2 = np.append(a2,[[70,80,90]],axis=0)  #here 0 means row and 1 means column
print(arr2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
arr2[1,0]=38
arr2[1,2] = 62
arr2[2,1]=87
arr2[0,2]=56
arr2[0,1]=21
print(arr2)

[[10 21 56]
 [38 50 62]
 [70 87 90]]


In [ ]:
a3 = np.delete(arr2,1,axis=1)
print(a3)

[[10 56]
 [38 62]
 [70 90]]


**Seraching and sorting**

In [3]:
arr = np.array([23,2,1,8,11])
a1 = np.sort(arr)
print(a1)

[ 1  2  8 11 23]


In [5]:
d2 = np.array([[23,2,1],[8,11,4]])
d3 = np.sort(d2,axis=0)
print(d3)

[[ 8  2  1]
 [23 11  4]]


In [7]:
ard = np.array([30,40,50,40])
np.where(ard==40)

(array([1, 3]),)

In [11]:
d5 = np.array([1,2,4,5,7])
np.searchsorted(d5,6)

np.int64(4)

**Reshape and resize**

In [ ]:
#convertig 2d into 1d
f6 = np.array([[30,40],[50,60]])
a4 = f6.flatten()
print(a4)

[30 40 50 60]


In [16]:
f7 = np.array([20,30,40,50,60,70])
a9 = f7.reshape(3,2)
print(a9)

[[20 30]
 [40 50]
 [60 70]]
