This is Jupyter notebook file

In [9]:
print("Hello world")

Hello world


In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Numerical Python also known as numpy is used for numericalvalues it's 50x more daster than python list is mainly used in data analytics and it was created in 2005 and created by travis oliphant and its deep down written in c++ language

In [1]:
#here we import numpy
import numpy as np

In [15]:
arr  = np.array([22,45,89,90,'wasiq'])
print(arr[-1])

wasiq


In [16]:
ar2 = np.array([33,78,91,101,87,34])
print(ar2[1:4])

[ 78  91 101]


In [9]:
arr = np.array([21,22,76,19,101])
print(arr[-1])

101


It' 1-d array

In [10]:
arr2 = np.array([101,65,82,11,79,201,111])
print(arr2[1:5])

[65 82 11 79]


2D Dimension

In [26]:
arr4 = np.array([[22,11,32,11],[12,91,89,31]])

print(arr4.ndim)
print(type(arr4))
print(arr4)

2
<class 'numpy.ndarray'>
[[22 11 32 11]
 [12 91 89 31]]


**Statstical operations**

In [10]:
ar1 = np.array([21,11,32,47,90])

In [ ]:
np.mean(ar1)  #here we get average

np.float64(40.2)

In [ ]:
np.max(ar1)  #here we get maximum value

np.int64(90)

In [ ]:
np.min(ar1)   #here we get minimum value

np.int64(11)

In [ ]:
np.sum(ar1)  #here we ge sum of all values

np.int64(201)

**Mathematical operation**

In [26]:
a = np.array([8,10,3,25])
b = np.array([2,7,6,1])

In [16]:
np.add(a,b)

array([10, 17,  9,  6])

In [17]:
np.subtract(a,b)

array([ 6,  3, -3,  4])

In [18]:
np.multiply(a,b)

array([16, 70, 18,  5])

In [19]:
np.divide(a,b)

array([4.        , 1.42857143, 0.5       , 5.        ])

In [20]:
np.power(a,2)

array([ 64, 100,   9,  25])

In [21]:
np.power(a,3)

array([ 512, 1000,   27,  125])

In [27]:
np.sqrt(a)

array([2.82842712, 3.16227766, 1.73205081, 5.        ])

**Data Manipulation**

In [5]:
arr = np.array([1,2,3,4,5])
a1 = np.append(arr,[6,7,8,9,10])
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
arr1 = np.array([[10,20,30],[40,50,60]])
a2 = np.append(arr1,[[70,80,90]],axis=0)
print(a2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
a2[1,1] = 55
a2[2,2] = 99
a2[0,0] = 100
a2[0,2] = 35
a2[1,0] = 44
print(a2)

[[100  20  35]
 [ 44  55  60]
 [ 70  80  99]]


In [ ]:
#delete
a3 = np.delete(a2,2,axis=1)
print(a3)

[[100  20]
 [ 44  55]
 [ 70  80]]


**Searching and sorting**

In [22]:
ar1 = np.array([5,8,2,9,3])
arr = np.sort(ar1)
print(arr)

[2 3 5 8 9]


In [26]:
d_arr = np.array([[3,20],[55,4]])
np.sort(d_arr,axis=0)


array([[ 3,  4],
       [55, 20]])

In [28]:
ar55 = np.array([20,78,78,90])
np.where(ar55 ==78)


(array([1, 2]),)

In [31]:
ar11 = np.array([1,2,4,5,7])
np.searchsorted(ar11,6)

np.int64(4)

**Reshape and resize**

In [35]:
arr_f = np.array([[10,20],[30,40]])
arr_x= arr_f.flatten()
print(arr_x)

[10 20 30 40]


In [ ]:
ar4 = np.array([1,2,3,4,5,6])
aa = ar4.reshape(3,2)
print(aa.ndim)

2


**Random Number genrating**

In [ ]:
x = np.random.rand(3)  #here we get output in 0 to 1
print(x)

[0.30207686 0.08643007 0.68870387]


In [ ]:
z = np.random.randint(1,20,size=3)  #here we get range based
print(z)

[17 19 14]


In [ ]:
y = np.random.randint(1000,9999,size=2)  #here we get 4 digit otp
print(y)

[6629 9304]


In [ ]:
xy = np.random.randint(100000,999999,size = 4)  #here we get 6 digit otp
print(xy)

[346433 115586 152364 893427]


In [ ]:
z1 = np.random.randn()  #here we get output between poitive and negative
print(z1)

0.0457236400334276
