In [ ]:
#Here we download numpy by using pip
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


**Numerical Python also know as numpy was created by scientist namely travis oliphan in 2005 his main motive was to reduce the time complexity so thats why he create a numpy array which basically works like normal python list but it's 50x faster than normal python list**

In [1]:
#Here we inmport numpy
import numpy as np

**Numpy array stores multiple items in a single variable. It's Homegenous**

In [11]:
arr = np.array([2,56,89,11])
print(arr[1])
print(arr[-1])
print(arr[1:3])
print(arr[1:])
print(arr[:3])
print(arr[: :-1])

56
11
[56 89]
[56 89 11]
[ 2 56 89]
[11 89 56  2]


In [4]:
ar1 = np.array([22,78,90,61,23])
print(ar1.ndim)

1


In [7]:
#2D array
ar2 = np.array([[33,11,89,51,'wasiq'],[39,78,10,9,'umer']])
print(ar2)
print(ar2[0][2])
print(ar2[1][2])

[['33' '11' '89' '51' 'wasiq']
 ['39' '78' '10' '9' 'umer']]
89
10


In [16]:
#3D array
ar3 = np.array([  [[21,45,89,22],[101,49,19,72]] ,       [[90,99,54,21],[1,5,69,32]]   ])
print(ar3[0][1][3])
print(ar3[0][0][2])
print(ar3[1][0][3])

72
89
21


**Satistical Operation**

In [ ]:
a2 = np.array([23,78,90,11,34])
# np.sum(a2)  #here we get total sum of the array
# np.max(a2)  #Here we get maximum value
# np.min(a2)  #Here we get minimum value
# np.mean(a2)  #Here we get average

np.float64(47.2)

**Mathematical Operation**

In [21]:
a3 = np.array([21,34,79,10])
a4 = np.array([32,6,1,12])

In [22]:
np.add(a3,a4)

array([53, 40, 80, 22])

In [23]:
np.subtract(a3,a4)

array([-11,  28,  78,  -2])

In [24]:
np.multiply(a3,a4)

array([672, 204,  79, 120])

In [25]:
np.divide(a3,a4)

array([ 0.65625   ,  5.66666667, 79.        ,  0.83333333])

In [2]:
a5 = np.array([12,4,18,6,8])

In [ ]:
np.power(a5,2) #here we find squre of the arry
np.power(a5,3) #here we find cube of the array

array([1728,   64, 5832,  216,  512])

In [ ]:
np.sqrt(a5)  #here we find the squre root of an array

array([3.46410162, 2.        , 4.24264069, 2.44948974, 2.82842712])

In [ ]:
x = np.random.rand()  #Here random rand give by defualt value from 0 to 1
print(x)

0.8449653470004268


In [ ]:
y = np.random.rand(5) #here we genrate five random numers
print(y)

[0.31186461 0.18266413 0.34395552 0.27370632 0.43148564]


In [ ]:
z = np.random.randint(1,10, size=4) #here we genrating randon numbers in range from 1 to 10 and we using size for genrating many numbers
print(z)

[8 4 8 7]


In [ ]:
u = np.random.randint(1000,9999, size=3)  #here we are genatin a otp of 4 digits
print(u)

[4490 9782 3533]


In [143]:
t = np.random.randint(100000,999999)
print(t)

360423


In [169]:
l = np.random.randn()  #here we get default value from negative to positive
print(l)

-0.8433670120154128


In [ ]:
#Reshape
a9 = np.array([11,89,64,51,91,22]) #here we convert 1d array into 2d array
new_array = a9.reshape(2,3)
print(new_array)

[[11 89 64]
 [51 91 22]]
