**Numerical Python which is also known as Numpy. it have a concept called numpy array which is basically 50X faster than traditional python list. It was created in 2005 by a developer called travis oliphant, it's is widely for the speed and data consistency**

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
arr = np.array([21,45,90,'wasiq'])
print(arr)

['21' '45' '90' 'wasiq']


In [2]:
ar1 = np.array([21,45,90])
print(ar1.ndim)

1


In [3]:
ar3 = np.array([[21,34,45],[11,76,10],[11,76,10]])
print(ar3)

[[21 34 45]
 [11 76 10]
 [11 76 10]]


In [9]:
ar3 = np.array([1, 2, 3,21,34,45,11,76,10,11,76,10])
# print(ar3[3:7])
# print(ar3[3:])
print(ar3[0:12:2])
print(ar3[::-2])

[ 1  3 34 11 10 76]
[10 11 76 45 21  2]


In [18]:
ar3 = np.array([[21,34,45],[11,76,10],[11,76,10]])
# print(ar3)
print(ar3[1][0])

11


**Stastical operation**

In [ ]:
ar3 = np.array([1, 2, 3,21,34,45,11,76,10,11,76,10])
np.max(ar3)  #maximum value
np.mean(ar3)  #average value
np.min(ar3)  #minimum value
np.sum(ar3)  #sum of all item
np.median(ar3)  #middle value

np.float64(1.1)

**Mathamaitical operation**

In [26]:
ar1 = np.array([2,4,6])
ar2 = np.array([8,9,10])
np.add(ar1,ar2)

array([10, 13, 16])

In [27]:
np.subtract(ar1,ar2)

array([-6, -5, -4])

In [28]:
np.multiply(ar1,ar2)

array([16, 36, 60])

In [29]:
np.divide(ar1,ar2)

array([0.25      , 0.44444444, 0.6       ])

In [ ]:
x = np.random.rand()  #rand gives by default number between 0 to 1
print(x)

0.609293174713537


In [ ]:
x = np.random.rand(5)   
print(x)

[0.86704837 0.54146364 0.40055643 0.16705656 0.41895169]


In [62]:
y = np.random.randint(1,10)
print(y)

5


In [80]:
z = np.random.randint(1000,9999,size=3)
print(z)

[2416 5105 6569]


In [101]:
z1 = np.random.randint(100000, 9999999)
print(z1)

7431183


In [118]:
z2 = np.random.randn()
print(z2)

0.6473581370862865


In [120]:
a1 = np.array([21,56,90,10,34,29])
new_arry = a1.reshape(3,2)
print(new_arry)

[[21 56]
 [90 10]
 [34 29]]
