Numerical Python is a Python libarary which is also known as numpy, its basically 50x faster than normal python list. it was created in 2005 by developer named travis oliphant, it get widely used due its speed 
and consistency data 

In [ ]:
#here we install numpy
!pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [5]:
print("Hello world!")

Hello world!


In [8]:
print("Hello Aiman!")

Hello Aiman!


In [11]:
ar2 = np.array([23,78,89,32,47,11,'wasiq'])
print(ar2)

['23' '78' '89' '32' '47' '11' 'wasiq']


In [10]:
arr = np.array([12,89,67,90,11])
print(arr[1:4])
print(arr[-2])

[89 67 90]
90


To know the total number of dimesion of numpy array

In [12]:
ar1 = np.array([21,54,89,93,59,90])
# print(ar1[1:])
print(ar1.ndim)

1


2D Array

In [6]:
a2 = np.array([[12,34,67,89],[91,11,85,98]])
print(a2[0][1])
print(a2[1][2])
print(a2.ndim)

34
85
2


3D array

In [11]:
a3 = np.array([  [[11,90,33],[41,65,32]],     [[12,65,98],[13,2,6]]  ])
print(a3[0][1][1])
print(a3[1][0][2])
print(a3[1][1][1])
print(a3.ndim)

65
98
2
3


**Statistical operation**

In [ ]:
aq = np.array([21,3,4,11])
np.sum(aq)  #Total sum
np.mean(aq)   #Average value
np.min(aq)   #minimum value
np.max(aq)  # maximum value

np.int64(21)

**Mathematical operation**

In [4]:
a = np.array([21,11,4,7,2])
b = np.array([8,5,22,9,10])

In [5]:
np.add(a,b)

array([29, 16, 26, 16, 12])

In [ ]:
np.subtract(a,b)

array([ 13,   6, -18,  -2,  -8])

In [7]:
np.multiply(a,b)

array([168,  55,  88,  63,  20])

In [8]:
np.divide(a,b)

array([2.625     , 2.2       , 0.18181818, 0.77777778, 0.2       ])

In [ ]:
np.power(a,2)  #when we want to find square
np.power(a,3)  #when we want tofind cube

array([9261, 1331,   64,  343,    8])

In [11]:
np.sqrt(a)

array([4.58257569, 3.31662479, 2.        , 2.64575131, 1.41421356])

In [ ]:
x =np.random.rand()  #when we want to genrate a number when we use rand and it gives defualt value from 0 to 1
print(x)

0.5063498253852565


In [ ]:
y = np.random.rand(5)  # when want to genrate five random numbers
print(y)

[0.87248547 0.09338612 0.56114923 0.25172458 0.96547973]


In [ ]:
z = np.random.randint(1,10,size=3) #when we want to genrate a random number 1 to 10 and size should be 3
print(z)

[1 9 4]


In [ ]:
z1 = np.random.randint(1000,9999)  #when we want to genrate a randon number of 4 digits
print(z1)

9893


In [78]:
j2 = np.random.randn()
print(j2)

-0.5485115824653416


**Here we reshaping the structure of data**

In [52]:
a3 = np.array([1,2,3,4,5,6])
arr_new = a3.reshape(3,2)
print(arr_new)

[[1 2]
 [3 4]
 [5 6]]
